import { motion } from 'framer-motion';
import Projets from '../components/Projets'
import Link from 'next/link'
import Head from 'next/head';
import Three from '../components/Three';
import Header from '../components/Header';

export default function Home({ imageDetails, transition }) {

  return (
    <div>
      <Head>
        <title>Antunes Benoit | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    	
      <Header />
      <Three />

      {/* <div className='flex justify-center items-center'>
        <motion.div className='mt-10'>
          <motion.div exit={{ opacity: 0 }} transition={transition} className='text-center mb-10'>
            <h2 className='text-3xl'>Qui suis-je ?</h2>
          </motion.div>
          <Link href='/moi'>
            <div className='overflow-hidden'               
            style={{
                width: imageDetails.width,
                height: imageDetails.height,
            }}>
                <motion.img whileHover={{ scale: 1.1 }} transition={transition} className='cursor-pointer' src="https://external-preview.redd.it/JyVV5DgtU49IwsN5ibdL_OFTthSjdvBbxpRNAgc_Z-E.jpg?width=640&crop=smart&auto=webp&s=ed0b0759f34da31e42af48a7a136c819279306d3" alt="" />
            </div>
          </Link>
        </motion.div>
      </div> */}
      
      <Projets />
    </div>
  )
}
